Feature/aa #0.2.1 4 back class product packaging brand enum category
FantastiSquad/wasteApp pull request #19
Opened 2020-06-04 14:58 UTC by anaKnell

Add:
Class Product - Brand - Enum Category
Repository Product
Service Interface product ans service product
Controller Product

Modified:
Class Packaging : add attributes

2020-06-04 16:36 UTC, Samuel-Huguet requested changes

2020-06-04 16:36 UTC, Samuel-Huguet commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/models/services/ProductService.java
> +    Optional<List<Product>> getProducts();
Peut être qu'il faudrait garder une cohérence dans le nom des méthodes GET ? A discuter mais rien d'alarmant non plus.

2020-06-04 16:36 UTC, Samuel-Huguet commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/models/services/ProductServiceImpl.java
> +        return true;
Faire les vérifications dans le service ce n'est pas l'habitude que l'on a eu. A discuter car je ne sais pas vraiment quelle est la meilleure pratique

2020-06-04 16:36 UTC, Samuel-Huguet commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/controllers/ProductController.java
> +    public ResponseEntity<List<Product>> getProduct(){
```suggestion
    public ResponseEntity<List<Product>> getProducts(){
```
ou 
```suggestion
    public ResponseEntity<List<Product>> getAllProducts(){
```

2020-06-04 16:36 UTC, Samuel-Huguet commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/controllers/ProductController.java
> +       List<Product> products = service.getProducts().orElseThrow(()-> new ResponseStatusException(HttpStatus.BAD_REQUEST, "something wrong with findAll(getProducts) method, maybe take a look on your
A discuter entre nous mais je ne suis pas sûr que l'exception soit levée un jour, mise à part si la table n'existe pas peut être

2020-06-04 16:36 UTC, Samuel-Huguet commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/controllers/ProductController.java
> +    return new ResponseEntity<>(productUpdated,HttpStatus.OK);
Très joli ça ! Ca fait du bien de ne plus voir les setter à tout va :)

2020-06-04 16:36 UTC, Samuel-Huguet commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/controllers/ProductController.java
> +    public ResponseEntity<Product> updateProduct(@Valid @PathVariable(value = "id") Long id, @RequestBody Product product){
Il faut peut être vérifier que le produit existe via son id avant de faire la sauvegarde ?

2020-06-04 16:36 UTC, Samuel-Huguet commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/models/services/ProductServiceImpl.java
> +    private static final String REQUEST_PUT = "put";
Tu te sers de ces variables ? J'ai pas eu l'impression mais j'ai peut être mal vu. Si tu ne les utilises pas autant les enlever

2020-06-04 18:36 UTC, anaKnell commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/controllers/ProductController.java
> +    public ResponseEntity<Product> updateProduct(@Valid @PathVariable(value = "id") Long id, @RequestBody Product product){
Avec cette méthode, il le fait:
* param: id != id data ->création d'un nouveau produit
* paam: id == id data ->update du produit
*param: id pas existant dans la BD: création d'un nouveau produit

2020-06-04 18:37 UTC, anaKnell commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/controllers/ProductController.java
> +    return new ResponseEntity<>(productUpdated,HttpStatus.OK);
@pfouque06

2020-06-04 18:37 UTC, anaKnell commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/models/services/ProductServiceImpl.java
> +    private static final String REQUEST_PUT = "put";
un oubli de ma part

2020-06-05 13:29 UTC, anaKnell commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/models/services/ProductService.java
> +    Optional<List<Product>> getProducts();
Done

2020-06-05 13:30 UTC, anaKnell commented on src/wasteApp_server/src/main/java/com/fantastiSquad/wasteApp/controllers/ProductController.java
> +       List<Product> products = service.getProducts().orElseThrow(()-> new ResponseStatusException(HttpStatus.BAD_REQUEST, "something wrong with findAll(getProducts) method, maybe take a look on your
vu au daily

2020-06-10 14:37 UTC, Samuel-Huguet approved these changes

2020-06-10 14:43 UTC, merged